In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [85, 90, 88, 92],
    "Age": [25, 30, 35, 40]
}

df = pd.DataFrame(data)
df

      Name  Marks  Age
0    Alice     85   25
1      Bob     90   30
2  Charlie     88   35
3    David     92   40

In [12]:
#Fetching all the rows and columns
# df.loc[:]
# df.loc[row, column] here we use column names and row number
# df.iloc[row, column] here we use column number and also row number
df.iloc[: , 0:2]

      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     88
3    David     92

In [10]:
df.loc[1, "Marks"]

np.int64(90)

In [11]:
df.iloc[1, 1]

np.int64(90)

In [ ]:
#