In [1]:
import numpy as np
import pandas as pd

In [40]:
data = {
    "Name": ["Alice", "Bob", "Charlie", None],
    "Age": [25, np.nan, 34, 42],
    "Salary": [25000, 30000, 35000, 40000]
}

df = pd.DataFrame(data)
df

      Name   Age  Salary
0    Alice  25.0   25000
1      Bob   NaN   30000
2  Charlie  34.0   35000
3     None  42.0   40000

In [41]:
# returns True where value is missing
df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False   False
3   True  False   False

In [42]:
df.isnull().sum()

Name      1
Age       1
Salary    0
dtype: int64

In [43]:
df.isnull().sum().sum()

np.int64(2)

In [44]:
(df.isnull().sum() / len(df)) * 100

Name      25.0
Age       25.0
Salary     0.0
dtype: float64

In [32]:
# returns False where value is missing
df.notnull()

    Name    Age  Salary
0   True   True    True
1   True  False    True
2   True   True    True
3  False   True    True

In [33]:
mean = df["Age"].mean()
df["Age"].fillna(mean, inplace=True)
df

C:\Users\Mangirish\AppData\Local\Temp\ipykernel_2760\4252803996.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(mean, inplace=True)

      Name        Age  Salary
0    Alice  25.000000   25000
1      Bob  33.666667   30000
2  Charlie  34.000000   35000
3     None  42.000000   40000

In [34]:
df.replace(25, 26, inplace=True)

In [35]:
df

      Name        Age  Salary
0    Alice  26.000000   25000
1      Bob  33.666667   30000
2  Charlie  34.000000   35000
3     None  42.000000   40000

In [36]:
data = {
    "Name": ["Alice", "Bob", "Charlie", None],
    "Age": [25, np.nan, 34, 42],
    "Salary": [25000, np.nan, 35000, 40000]
}

df = pd.DataFrame(data)

changed = df.interpolate(method="linear", inplace=False)
changed

C:\Users\Mangirish\AppData\Local\Temp\ipykernel_2760\523734884.py:9: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  changed = df.interpolate(method="linear", inplace=False)

      Name   Age   Salary
0    Alice  25.0  25000.0
1      Bob  29.5  30000.0
2  Charlie  34.0  35000.0
3     None  42.0  40000.0

In [37]:
data = {
    "Name": ["Alice", "Bob", "Charlie", None],
    "Age": [25, np.nan, 34, 42],
    "Salary": [25000, np.nan, 35000, 40000]
}

df = pd.DataFrame(data)

changed = df.dropna(inplace=False)
changed

      Name   Age   Salary
0    Alice  25.0  25000.0
2  Charlie  34.0  35000.0

In [38]:
changed = df.dropna(axis = 0, inplace=False)
changed

      Name   Age   Salary
0    Alice  25.0  25000.0
2  Charlie  34.0  35000.0

In [ ]:
# What are null values? NaN and NotNull
# Why missinng values are a common issue in machine learning
# How missing values can pose a significant challenge in data analysis
# Checking for missing values in pandas dataframe 
# write the syntax for the following with an example: isnull, notnull, fillna, replace, interpolation, dropna